-- ============================================================
-- 意见反馈功能 · Supabase (PostgreSQL) 建表脚本
-- 项目：蓝喜阳个人主页（第三版 · 黄白杂志风 + 意见反馈）
--
-- 使用方式：
--   1. 打开 Supabase 控制台 → 左侧 SQL Editor → New query
--   2. 把本文件全文粘贴进去 → 点 Run
--   3. 看到 "Success. No rows returned" 即建表成功
--   4. 本脚本已剔除在该编辑器里无法执行的内容（CREATE FUNCTION / CREATE TRIGGER，
--      详见第 3 节实测结论），全文可直接粘贴，不会出现语法错误
--   5. 时间默认值用 current_timestamp（关键字、不带括号），
--      避免复制过程中 now() 的括号丢失，导致
--      「ERROR: 0A000: cannot use column reference in DEFAULT expression」（LINE 13: default now,）
--
-- 本脚本可重复执行，不会清空已有数据。
-- 与 db/schema.sql（SQLite 本地版）字段设计一致，只是语法换成 Postgres。
--
-- 访客要填的 5 项（第 5 项由数据库自动生成，页面不设输入框）：
--   ① 名字或昵称          -> name
--   ② 与主页主人的关系     -> relation
--   ③ 本条反馈针对的设备   -> device
--   ④ 反馈内容            -> message
--   ⑤ 提交时间            -> created_at（default now()）
--
-- 【第三版隐私约定】页面对访客"只写不读"：
--   · 网页端只允许提交（insert），没有任何读取调用，页面上不显示任何人的反馈；
--   · 因此访客既看不到别人的内容，也改不了、删不掉（详见第 4 节 RLS）；
--   · 作者本人两种方式查看：Supabase 控制台 → Table Editor → feedback（不受 RLS 限制），
--     或用 service_role key 走 API；写完在网页端配合"导出 CSV"即可整理成表格。
-- ============================================================


-- ------------------------------------------------------------
-- 1. feedback：访客意见反馈表
-- ------------------------------------------------------------
create table if not exists public.feedback (
    id          bigint      generated by default as identity primary key,  -- 主键，自增
    name        text,                                                      -- ① 名字或昵称（可选）
    relation    text,                                                      -- ② 与主页主人的关系（可选）
    device      text,                                                      -- ③ 本条反馈针对的设备（可选）
    contact     text,                                                      -- 邮箱/微信（可选）
    category    text        not null default 'other',                      -- 反馈类型
    rating      smallint,                                                  -- 满意度 1-5（可选）
    message     text        not null,                                      -- ④ 反馈正文（必填）
    page_url    text,                                                      -- 提交来源页面
    user_agent  text,                                                      -- 浏览器/设备信息
    status      text        not null default 'new',                        -- 处理状态
    created_at  timestamptz not null default current_timestamp,                        -- ⑤ 提交时间（自动）
    updated_at  timestamptz not null default current_timestamp,                        -- 最近变更时间

    -- 取值约束：反馈类型只能是这四种
    constraint ck_feedback_category
        check (category in ('bug', 'suggestion', 'content', 'other')),
    -- 取值约束：处理状态只能是这三种
    constraint ck_feedback_status
        check (status in ('new', 'read', 'resolved')),
    -- 取值约束：评分要么不填，要么 1-5
    constraint ck_feedback_rating
        check (rating is null or (rating between 1 and 5)),
    -- 取值约束：正文不能空白，且限长（防滥用）
    constraint ck_feedback_message
        check (char_length(btrim(message)) between 1 and 1000),
    -- 取值约束：称呼与联系方式限长
    constraint ck_feedback_name_len
        check (name is null or char_length(name) <= 60),
    constraint ck_feedback_contact_len
        check (contact is null or char_length(contact) <= 120),
    -- 取值约束：与主页主人的关系只能是这几种
    -- 注：已建好的库要把 online(网友) 改成 lover(恋人)，需另跑 db/migration_relation_lover.sql
    --     （check 约束不能就地改，必须 drop + add）
    constraint ck_feedback_relation
        check (relation is null or relation in
               ('classmate', 'friend', 'family', 'teacher', 'lover', 'other')),
    -- 取值约束：本条反馈针对的设备只能是这几种
    constraint ck_feedback_device
        check (device is null or device in
               ('phone', 'tablet', 'computer', 'other'))
);

comment on table  public.feedback            is '个人主页访客意见反馈';
comment on column public.feedback.name       is '① 名字或昵称（可空，页面默认署名「匿名访客」）';
comment on column public.feedback.relation   is '② 与主页主人的关系：classmate=同学 / friend=朋友 / family=家人 / teacher=老师 / lover=恋人 / other=其他';
comment on column public.feedback.device     is '③ 本条反馈针对的设备：phone=手机 / tablet=平板 / computer=电脑 / other=其他设备';
comment on column public.feedback.message    is '④ 反馈内容（必填，1-1000 字）';
comment on column public.feedback.created_at is '⑤ 提交时间（由数据库自动写入）';
comment on column public.feedback.category   is 'bug=问题 / suggestion=建议 / content=内容 / other=其他';
comment on column public.feedback.status     is 'new=未读 / read=已读 / resolved=已处理';


-- ------------------------------------------------------------
-- 2. 索引：支撑"按时间倒序看列表""按状态筛选"
-- ------------------------------------------------------------
create index if not exists idx_feedback_created_at on public.feedback (created_at desc);
create index if not exists idx_feedback_status     on public.feedback (status);


-- ------------------------------------------------------------
-- 3.（可选，默认关闭 / 整段注释）自动维护 updated_at
--
--    ⚠️ 实测结论：Supabase SQL Editor 无法执行 CREATE FUNCTION / CREATE TRIGGER，
--       一律报「ERROR: 42601: syntax error at or near "returns"」（LINE 45: returns trigger）。
--       它是把这类语句切错位置后再发送的，因此：
--         · 用 $$ ... $$ 美元引用包裹函数体 → 仍报错；
--         · 换成单引号包裹函数体（as 'begin ... end'）→ 仍然报错。
--       所以本段【默认整段注释掉】，保证脚本能一次跑通。
--
--    想要 updated_at 自动更新时：把下面 9 行前面的 "-- " 去掉，
--    单独【新开一个 query】只跑这一段，不影响已经建好的表。
--    不跑也完全不影响反馈功能 —— 访客只能 insert，updated_at 走 default now()。
-- ------------------------------------------------------------
-- create or replace function public.touch_feedback_updated_at()
-- returns trigger
-- language plpgsql
-- as 'begin new.updated_at = now(); return new; end';
-- drop trigger if exists trg_feedback_updated_at on public.feedback;
-- create trigger trg_feedback_updated_at
--     before update on public.feedback
--     for each row
--     execute function public.touch_feedback_updated_at();


-- ------------------------------------------------------------
-- 4. 行级安全（RLS）—— 这一步不做，你的反馈会被任何人读走
-- ------------------------------------------------------------
alter table public.feedback enable row level security;

-- 匿名访客（页面里的 anon key）：只允许"提交"，并且只能提交 new 状态的记录
drop policy if exists "anon can submit feedback" on public.feedback;
create policy "anon can submit feedback"
    on public.feedback
    for insert
    to anon
    with check (status = 'new');

-- ⚠️ 这里【故意不创建】select 策略。
--    PostgreSQL 的 RLS 是"默认拒绝"：没有 select 策略 = 匿名角色读不到任何一行。
--    因此即使 anon key 公开在网页源码里，别人也无法把你的反馈读走。
--    你自己在 Supabase 控制台（Table Editor）看数据不受 RLS 限制。


-- ------------------------------------------------------------
-- 4.5 明确授予匿名角色「最小必要权限」
--     Supabase 部分新项目不再自动给 public 架构里的表授予 anon 表级权限，
--     缺少这一步时页面提交会报 42501「permission denied for table feedback」。
--     这里【只授 insert】—— 不授 select / update / delete，
--     等于在 RLS 之外再加一层表级权限保护。
-- ------------------------------------------------------------
grant usage  on schema public          to anon;
grant insert on table public.feedback  to anon;


-- ------------------------------------------------------------
-- 5. 如果表是【更早版本】建的（还没有 relation / device 两列）
--    —— 执行下面两行即可补上，不影响已有数据。建表语句里已有这两列的话，跳过即可。
-- ------------------------------------------------------------
alter table public.feedback add column if not exists relation text;
alter table public.feedback add column if not exists device   text;


-- ------------------------------------------------------------
-- 6. 建好后自检（可选）：确认表、字段、索引、策略都在位
-- ------------------------------------------------------------
select
    (select count(*) from information_schema.tables
      where table_schema = 'public' and table_name = 'feedback')  as table_ok,
    (select count(*) from information_schema.columns
      where table_schema = 'public' and table_name = 'feedback'
        and column_name in ('name', 'relation', 'device', 'message', 'created_at')) as five_fields_ok,
    (select count(*) from pg_indexes
      where schemaname = 'public' and tablename = 'feedback')     as index_count,
    (select count(*) from pg_policies
      where schemaname = 'public' and tablename = 'feedback')     as policy_count,
    (select relrowsecurity from pg_class
      where oid = 'public.feedback'::regclass)                    as rls_enabled;
-- 期望结果：table_ok=1，five_fields_ok=5，index_count=3（1 个主键 + 2 个自建），
--          policy_count=1，rls_enabled=true
